### ISSUE TITLE
Probleme mit Zeilenabständen und Schriftart

### ISSUE THREAD

**Issue by sarah-may** [Teamarbeit-in-IT-Lehrveranstaltungen/Digitaler-Wegweiser#1]
@andre-dietrich 
 
Ich habe Probleme das mit den Zeilenabständen umzusetzen. Ich habe ein CSS-Dokument angelegt nach deinem Beispiel und das eingefügt, aber leider verändert sich nicht. Ich konnte meinen Fehler leider selbst nicht finden. Ähnlich sieht es beim ändern der Schriftart aus. Ich vermute mir entgeht bei beiden irgendetwas. Könntest du mir da noch mal aushelfen oder das erklären (Wie deine Zeit es hergibt)? Es liegt alles in unserem Projekt unter dem Repository "Digitaler Wegweiser".

Liebe Grüße
Sarah

**Comment by andre-dietrich** [comment]
Hallo Sarah,

ich habe den Verweis auf die lokale Datei gelenkt, ich glaube das Problem lag daran, dass es sich dabei nicht um die "raw"-Datei gehandelt hat. Aber alles was im Projekt liegt, sollte auch ohne http davor angesprochen werden können ...

https://github.com/Teamarbeit-in-IT-Lehrveranstaltungen/Digitaler-Wegweiser/commit/b1f683e0b3a90c18c3b695636e6c829527bf0d67

**Comment by sarah-may** [comment]
Hallo André,
danke dir!

**Comment by andre-dietrich** [comment]
Sehr gerne ;-)
