### ISSUE TITLE
Grafikidee Navigation

### ISSUE THREAD

**Issue by sarah-may** [Teamarbeit-in-IT-Lehrveranstaltungen/Digitaler-Wegweiser#2]
@andre-dietrich 
@anja-bot hatte folgende Idee: 

_"Damit es noch besser strukturiert ist (visuell), habe ich überlegt, ob wir Abbildungen einfügen sollten, die links an der Seite liegen oder oben oder … und dem Lesenden zeigen, wo man grade ist. Sowas längliches, was z.B. Icons für „Aus der Forschung“, „Handlungsempfehlungen“, „am konkreten Beispiel“ zeigt (also immer nur das, was in dem Schritt bzw. Kapitel drin ist) und wo umrahmt ist, oder eingefärbt, wo man grade ist. Ist das prinzipiell in Lia möglich? Meinst du, dass hilft auch nochmal zu Orientierung?"_ 

Mit meinen LiaScript Kenntnissen ist das nicht möglich. Ich habe versucht eine Lösung drumherum zu finden (siehe Anhang). Das sieht nur leider sehr bescheiden aus. Ist das so oder so ähnlich, wie sie sich das vorstellt 
![Screenshot seitliche Navigation](https://github.com/Teamarbeit-in-IT-Lehrveranstaltungen/Digitaler-Wegweiser/assets/136444275/4e5b369a-9c03-41ce-b76b-916e126d846e)
möglich?

**Comment by andre-dietrich** [comment]
Hallo @anja-bot ... das ist eigentlich eine gute Idee, das LiaScript-Logo kann man mit dem folgenden Befehl ändern:

``` markdown
<!--
icon: http://Bild1.png
-->

# Titel

## Subsection
<!--
icon: http://anderesBild.svg
-->

...
```

Im Hauptkommtar das Bild zu ändern funktioniert, ich muss LiaScript nur erweitern, dass er die Änderungen, falls vorhanden, auch bezüglich der Bilder in den SubSections übernimmt ... Aber dass ist kein Problem ... Ich hatte nur noch keinen Anwendungsfall gesehen ...

Alternativ könnt ihr auch unicode-Zeichen also Emojies mit in die Überschriften aufnehmen, ich hatte das in der LiaScript-Doku gemacht um zu markieren, wo es unterschiede bezüglich der Standard-Markdown-Syntax gibt:

``` markdown
# 💥 Titel

## 🌡️ Thema 1
```

https://emojipedia.org/de/

Die werden wie normale Schriftzeichen behandelt und auch entsprechend größer und kleiner skaliert ...

Ich sage bescheid, wenn die `icon`-Sache drin ist ...

**Comment by sarah-may** [comment]
Hallo André,
das wäre ja super. Danke dir, dass du dich darum kümmerst. Das mit den Icons in den Überschriften wäre auch eine gute Alternative ich weiß aber nicht, ob Anja das reicht. Ich kann das aber mal ausprobieren.

**Comment by andre-dietrich** [comment]
Die Möglichkeit die Icons auf jeder Seite zu ändern, habe ich jetzt in LiaScript eingefügt ...

https://github.com/LiaScript/LiaScript/commit/b4010fbe2fbda75eacbd495093592089f8692adf

... ging ganz schnell. Ich muss es nur noch "ausrollen", sodass es in den Editoren und auf der Seite auch in der nächsten Version zur Verfügung steht ...

**Comment by sarah-may** [comment]
Hallo André,
danke dafür. 
Tut mir leid, aber ich verstehe leider nicht wie genau du das meinst was jetzt wie möglich ist. Meinst du die unicode-Icons können jetzt pro Seite an der Seite geändert werden? Wenn ja wie? Gibt es dafür nun ein Lia-Snipped? Oder lassen sich Bilder nun anders einfügen? Denn die Icons im Titel zu ändern ging ja vorher.

**Comment by andre-dietrich** [comment]
@sarah-may ... Hi, ich habe das Update gerade hochgeladen, kann sein, dass du das LiaScript-Plugin nochmal updaten musst. An der Stelle für Plugins müsste ein Blauer-Kreis erscheinen, wo dann sowas steht wie __reload required__ ... dann kannst für jede Überschrift ein eigenes Logo definieren, hier ein Beispiel:

``` markdown
<!--
icon: https://cdn-icons-png.flaticon.com/512/1998/1998681.png
-->

# Title

## SubTitle

## Changing Icon
<!--
icon: https://www.svgrepo.com/download/232660/lion.svg
-->

## Back to main


## Another Icon
<!--
icon: https://upload.wikimedia.org/wikipedia/commons/3/32/Beige_Elephant_Xogos_da_Meiga_chess_icons_family.svg
-->

```


Hier zum Experimentieren:

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA3WQP2vDMBDFd30KFc/SxTY1SQiFJmTo0KkduglVUmQR/cNSKvrtK5lChtLluPc47vfuDg+EICOC3+M555j2AEJ60pxEotf0Ynluiorg4LEfoN/ttmuZtj2tE4iQJ4Q6/G6yVbXp8Nvt8y5OM/faeI1f6hJ0+IsrpdD0pRcVw8qQoXgbuIRhHKZpA9ZUeB345XT4yMUV54AdNx6tzrMPeVbLv4hbbAtpMVfjlDSchkVDU7EpqFRXz4URxgGOymjFzlbFGjyzj6BDYpKz1+pzJmaVElu/wy7cGft9j/YDTkQG20sBAAA=

**Comment by sarah-may** [comment]
Hallo André,
danke jetzt habe ich es verstanden und direkt umgesetzt. 
Im Editor sieht es auch gut aus. Wenn ich die Seite über die Lia-Seite lade funktioniert es jedoch nicht. 

Und hier dann direkt noch zwei Fragen: 

1. Wenn wir das später veröffentlichen und mit Leuten teilen wollen lege ich dann einfach einen Classroomlink an und teile diesen? Oder gibt es noch eine andere Variante?
2. @anja-bot hat geschrieben: "Kapitel "Schritt für Schritt" ->  kann man das erste "am konkreten Beispiel" so formatieren, dass es keine Überschrift ist und somit nicht in der Gliederung auftaucht? -> die erste Unterüberschrift wäre somit "Schritt 1 ...". Ginge das ohne, dass "am konkreten Beispiel" auf die vorherige Seite gezogen wird? Damit man weniger scrollt wollte Anja das lieber auf zwei Seiten haben.

Tut mir leid, dass ich dich so mit fragen bombadiere. Wir sollten aber bald durch damit sein

Liebe Grüße 

Sarah

**Comment by andre-dietrich** [comment]
@sarah-may kein Problem, dafür bin ich ja da ;-)

Wahrscheinlich musst du nur nochmal die Seite neu mit <kbd>F5</kbd> laden. Die LiaScript-Seite speichert sich selber im Browser und bei Updates, kann es sein, dass diese erst beim 2ten mal durchkommen.

1. Der Klassenraum wird nur zwischen den Browsern direkt erzeugt, heißt, es wird nirgends wirklich gespeichert. Wenn du einen öffnest, dann kannst du die URL mit allen anderen Teilen, aber wenn ihr zeitversetzt drin seid, dann wird nichts synchronisiert. Du kannst also für jedesmal einen neuen Klassenraum erstellen und diesen teilen. _Es gibt jedoch eine Möglichkeit mit GunDB um die Räume dauerhaft zu erstellen, hier wird in einer Datenbank ein Satz abgelegt, die gehört jedoch nicht uns. Jeder kann das selber für sich hosten, oder man vertraut darauf, dass diese Daten länger gespeichert bleiben, ich habe noch nicht getestet, wie lange etwas drin bleibt..._
2. Ja das geht. Ihr könnt einfach eine `<section>` darum legen, das würde wie folgt aussehen:

``` markdown
# Titel

<section>

## Dieser Titel taucht  nicht in der Übersicht auf

foo bar
</section>
```

Liebe Grüße

André

**Comment by sarah-may** [comment]
Leider funktioniert trotz neu laden das mit den Icons bei mir nicht. Es müsste halt spätestens in der finalen Version funktionieren.

Das mit dem Link verstehe ich nur zum Teil. Ich habe Anja gebeten dir direkt noch mal deswegen zu schreiben. Da es wichtig für den Abschlussbericht ist, wäre es besser wenn ihr euch da absprecht und du dann genau das machen kannst was benötigt wird und nicht ich das mit meinem Halbwissen mache und dann funktioniert es nicht oder so.

Das mit der Section hatte ich tatsächlich schon versucht, aber es blieb trotzdem auf der gleichen Seite. Anja meinte aber wir lassen es jetzt einfach so.

**Comment by andre-dietrich** [comment]
Ach so ... die Seite soll nicht angezeigt werden? Also auch keinen Eintrag im Inhaltsverzeichnis generieren? Wie soll der Nutzer auf die Seite kommen?

**Comment by andre-dietrich** [comment]
Ach, ich hatte vergessen, die as LiaScript-Update zu pushen ... jetzt funktioniert es ...

**Comment by sarah-may** [comment]
> Ach so ... die Seite soll nicht angezeigt werden? Also auch keinen Eintrag im Inhaltsverzeichnis generieren? Wie soll der Nutzer auf die Seite kommen?

Es sollte nicht in der Gliederung sein, aber über das weiterklicken erreichbar sein. Wie gesagt es hat sich erledigt wir haben es anders gelöst und auf eine Seite gepackt.

**Comment by sarah-may** [comment]
> Ach, ich hatte vergessen, die as LiaScript-Update zu pushen ... jetzt funktioniert es ...

Super! Danke dir.
